/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-20 19:08:55 UTC)
 * on 2013-06-25 at 13:38:23 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.pttest;

/**
 * Service definition for Pttest (0.1).
 *
 * <p>
 * Store API for Public Transport Web Service
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PttestRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Pttest extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://skimmytest.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "pttest/0.1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Pttest(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Pttest(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "addstop".
   *
   * This request holds the parameters needed by the the pttest server.  After setting any optional
   * parameters, call the {@link Addstop#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.pttest.model.EndpointswsMessagesPositionedItemMessage}
   * @return the request
   */
  public Addstop addstop(com.google.api.services.pttest.model.EndpointswsMessagesPositionedItemMessage content) throws java.io.IOException {
    Addstop result = new Addstop(content);
    initialize(result);
    return result;
  }

  public class Addstop extends PttestRequest<com.google.api.services.pttest.model.EndpointswsMessagesReplyInfoMessage> {

    private static final String REST_PATH = "stop_insert";

    /**
     * Create a request for the method "addstop".
     *
     * This request holds the parameters needed by the the pttest server.  After setting any optional
     * parameters, call the {@link Addstop#execute()} method to invoke the remote operation. <p>
     * {@link
     * Addstop#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.pttest.model.EndpointswsMessagesPositionedItemMessage}
     * @since 1.13
     */
    protected Addstop(com.google.api.services.pttest.model.EndpointswsMessagesPositionedItemMessage content) {
      super(Pttest.this, "POST", REST_PATH, content, com.google.api.services.pttest.model.EndpointswsMessagesReplyInfoMessage.class);
    }

    @Override
    public Addstop setAlt(java.lang.String alt) {
      return (Addstop) super.setAlt(alt);
    }

    @Override
    public Addstop setFields(java.lang.String fields) {
      return (Addstop) super.setFields(fields);
    }

    @Override
    public Addstop setKey(java.lang.String key) {
      return (Addstop) super.setKey(key);
    }

    @Override
    public Addstop setOauthToken(java.lang.String oauthToken) {
      return (Addstop) super.setOauthToken(oauthToken);
    }

    @Override
    public Addstop setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Addstop) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Addstop setQuotaUser(java.lang.String quotaUser) {
      return (Addstop) super.setQuotaUser(quotaUser);
    }

    @Override
    public Addstop setUserIp(java.lang.String userIp) {
      return (Addstop) super.setUserIp(userIp);
    }

    @Override
    public Addstop set(String parameterName, Object value) {
      return (Addstop) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getstops".
   *
   * This request holds the parameters needed by the the pttest server.  After setting any optional
   * parameters, call the {@link Getstops#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.pttest.model.EndpointswsMessagesGeoPointWithAccuracyMessage}
   * @return the request
   */
  public Getstops getstops(com.google.api.services.pttest.model.EndpointswsMessagesGeoPointWithAccuracyMessage content) throws java.io.IOException {
    Getstops result = new Getstops(content);
    initialize(result);
    return result;
  }

  public class Getstops extends PttestRequest<com.google.api.services.pttest.model.EndpointswsMessagesPositionedItemListMessage> {

    private static final String REST_PATH = "stops";

    /**
     * Create a request for the method "getstops".
     *
     * This request holds the parameters needed by the the pttest server.  After setting any optional
     * parameters, call the {@link Getstops#execute()} method to invoke the remote operation. <p>
     * {@link
     * Getstops#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.pttest.model.EndpointswsMessagesGeoPointWithAccuracyMessage}
     * @since 1.13
     */
    protected Getstops(com.google.api.services.pttest.model.EndpointswsMessagesGeoPointWithAccuracyMessage content) {
      super(Pttest.this, "POST", REST_PATH, content, com.google.api.services.pttest.model.EndpointswsMessagesPositionedItemListMessage.class);
    }

    @Override
    public Getstops setAlt(java.lang.String alt) {
      return (Getstops) super.setAlt(alt);
    }

    @Override
    public Getstops setFields(java.lang.String fields) {
      return (Getstops) super.setFields(fields);
    }

    @Override
    public Getstops setKey(java.lang.String key) {
      return (Getstops) super.setKey(key);
    }

    @Override
    public Getstops setOauthToken(java.lang.String oauthToken) {
      return (Getstops) super.setOauthToken(oauthToken);
    }

    @Override
    public Getstops setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getstops) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getstops setQuotaUser(java.lang.String quotaUser) {
      return (Getstops) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getstops setUserIp(java.lang.String userIp) {
      return (Getstops) super.setUserIp(userIp);
    }

    @Override
    public Getstops set(String parameterName, Object value) {
      return (Getstops) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Pttest}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Pttest}. */
    @Override
    public Pttest build() {
      return new Pttest(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PttestRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPttestRequestInitializer(
        PttestRequestInitializer pttestRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(pttestRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
