/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-20 19:08:55 UTC)
 * on 2013-06-22 at 13:06:01 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.pttest.model;

/**
 * Model definition for EndpointswsMessagesReplyInfoMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EndpointswsMessagesReplyInfoMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long errorCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String info;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getErrorCode() {
    return errorCode;
  }

  /**
   * @param errorCode errorCode or {@code null} for none
   */
  public EndpointswsMessagesReplyInfoMessage setErrorCode(java.lang.Long errorCode) {
    this.errorCode = errorCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInfo() {
    return info;
  }

  /**
   * @param info info or {@code null} for none
   */
  public EndpointswsMessagesReplyInfoMessage setInfo(java.lang.String info) {
    this.info = info;
    return this;
  }

  @Override
  public EndpointswsMessagesReplyInfoMessage set(String fieldName, Object value) {
    return (EndpointswsMessagesReplyInfoMessage) super.set(fieldName, value);
  }

  @Override
  public EndpointswsMessagesReplyInfoMessage clone() {
    return (EndpointswsMessagesReplyInfoMessage) super.clone();
  }

}
