/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-20 19:08:55 UTC)
 * on 2013-06-25 at 13:38:23 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.pttest.model;

/**
 * Model definition for EndpointswsMessagesPositionedItemListMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EndpointswsMessagesPositionedItemListMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private EndpointswsMessagesReplyInfoMessage infoMessage;

  /**
   * This is the message representing Positioned Items, positioned items are defined at least by an
   * id, a position and a type. Other optional fields are: comments, pictures
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<EndpointswsMessagesPositionedItemMessage> items;

  static {
    // hack to force ProGuard to consider EndpointswsMessagesPositionedItemMessage used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(EndpointswsMessagesPositionedItemMessage.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public EndpointswsMessagesReplyInfoMessage getInfoMessage() {
    return infoMessage;
  }

  /**
   * @param infoMessage infoMessage or {@code null} for none
   */
  public EndpointswsMessagesPositionedItemListMessage setInfoMessage(EndpointswsMessagesReplyInfoMessage infoMessage) {
    this.infoMessage = infoMessage;
    return this;
  }

  /**
   * This is the message representing Positioned Items, positioned items are defined at least by an
   * id, a position and a type. Other optional fields are: comments, pictures
   * @return value or {@code null} for none
   */
  public java.util.List<EndpointswsMessagesPositionedItemMessage> getItems() {
    return items;
  }

  /**
   * This is the message representing Positioned Items, positioned items are defined at least by an
   * id, a position and a type. Other optional fields are: comments, pictures
   * @param items items or {@code null} for none
   */
  public EndpointswsMessagesPositionedItemListMessage setItems(java.util.List<EndpointswsMessagesPositionedItemMessage> items) {
    this.items = items;
    return this;
  }

  @Override
  public EndpointswsMessagesPositionedItemListMessage set(String fieldName, Object value) {
    return (EndpointswsMessagesPositionedItemListMessage) super.set(fieldName, value);
  }

  @Override
  public EndpointswsMessagesPositionedItemListMessage clone() {
    return (EndpointswsMessagesPositionedItemListMessage) super.clone();
  }

}
